import Foundation

let allQuestions: [QuizQuestion] = [
    // GÊNESIS E CRIAÇÃO
    QuizQuestion(id: 1, question: "Em quantos dias Deus criou o mundo, segundo o livro de Gênesis?", options: ["5 dias", "6 dias", "7 dias", "10 dias"], correctIndex: 1, explanation: "Deus criou o mundo em 6 dias e descansou no sétimo. O sétimo dia foi abençoado e santificado como o dia de descanso.", reference: "Gênesis 1:31 – 2:2", category: .genesis),
    QuizQuestion(id: 2, question: "Como se chamava o primeiro homem criado por Deus?", options: ["Noé", "Abraão", "Adão", "Moisés"], correctIndex: 2, explanation: "Deus formou o homem do pó da terra e soprou em suas narinas o fôlego de vida. O homem se chamava Adão.", reference: "Gênesis 2:7", category: .genesis),
    QuizQuestion(id: 3, question: "Qual era o nome da esposa de Adão?", options: ["Sara", "Eva", "Rute", "Ester"], correctIndex: 1, explanation: "Eva foi criada por Deus de uma costela de Adão para ser sua companheira. Adão a chamou de mulher, e depois de Eva, mãe dos viventes.", reference: "Gênesis 2:22-23, 3:20", category: .genesis),
    QuizQuestion(id: 4, question: "Quantos dias e noites durou o dilúvio no tempo de Noé?", options: ["20 dias e 20 noites", "30 dias e 30 noites", "40 dias e 40 noites", "50 dias e 50 noites"], correctIndex: 2, explanation: "Choveu sobre a terra por quarenta dias e quarenta noites. Noé, sua família e os animais foram preservados na arca que Deus mandou construir.", reference: "Gênesis 7:12", category: .genesis),
    QuizQuestion(id: 5, question: "Qual sinal Deus colocou no céu como aliança com Noé?", options: ["Uma estrela cadente", "Um arco-íris", "Uma nuvem brilhante", "Um raio"], correctIndex: 1, explanation: "Deus colocou o arco-íris nas nuvens como sinal de sua aliança: nunca mais haveria um dilúvio para destruir toda a vida.", reference: "Gênesis 9:13", category: .genesis),

    // JESUS E EVANGELHOS
    QuizQuestion(id: 6, question: "Em qual cidade Jesus nasceu?", options: ["Nazaré", "Jerusalém", "Belém", "Jericó"], correctIndex: 2, explanation: "Jesus nasceu em Belém da Judeia, cumprindo a profecia de Miquéias. José e Maria viajaram até lá para o recenseamento ordenado por Augusto César.", reference: "Lucas 2:4-7, Miquéias 5:2", category: .jesus),
    QuizQuestion(id: 7, question: "Quem batizou Jesus no rio Jordão?", options: ["Pedro", "Paulo", "João Batista", "Elias"], correctIndex: 2, explanation: "João Batista batizou Jesus no rio Jordão. Ao sair da água, o Espírito de Deus desceu sobre Jesus como uma pomba e uma voz do céu disse: 'Este é o meu Filho amado'.", reference: "Mateus 3:13-17", category: .jesus),
    QuizQuestion(id: 8, question: "Quantos discípulos Jesus escolheu para acompanhá-lo?", options: ["7", "10", "12", "70"], correctIndex: 2, explanation: "Jesus escolheu doze discípulos, chamados de apóstolos, para estar com ele e enviar a pregar o evangelho. O número doze representava as doze tribos de Israel.", reference: "Marcos 3:13-19", category: .jesus),
    QuizQuestion(id: 9, question: "Qual foi o primeiro milagre de Jesus registrado na Bíblia?", options: ["Caminhar sobre as águas", "Transformar água em vinho", "Multiplicar pães e peixes", "Ressuscitar Lázaro"], correctIndex: 1, explanation: "O primeiro milagre de Jesus aconteceu em Caná da Galileia, em um casamento, quando a pedido de sua mãe Maria, transformou água em vinho.", reference: "João 2:1-11", category: .jesus),
    QuizQuestion(id: 10, question: "Qual versículo fala do amor de Deus ao mundo inteiro?", options: ["João 1:1", "João 3:16", "Romanos 8:28", "Salmos 23:1"], correctIndex: 1, explanation: "João 3:16 diz: 'Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo aquele que nele crer não pereça, mas tenha a vida eterna.' Este versículo resume o evangelho.", reference: "João 3:16", category: .jesus),
    QuizQuestion(id: 11, question: "Quantos pães e peixes Jesus usou para alimentar 5.000 homens?", options: ["3 pães e 2 peixes", "5 pães e 2 peixes", "7 pães e 3 peixes", "10 pães e 5 peixes"], correctIndex: 1, explanation: "Jesus tomou 5 pães e 2 peixes, abençoou, e partiu para seus discípulos distribuírem. Todos os 5.000 homens comeram e sobraram 12 cestos cheios.", reference: "Mateus 14:17-21", category: .jesus),
    QuizQuestion(id: 12, question: "Quem traiu Jesus por 30 moedas de prata?", options: ["Pedro", "Tomé", "Judas Iscariotes", "Filipe"], correctIndex: 2, explanation: "Judas Iscariotes, um dos doze discípulos, traiu Jesus entregando-o aos sumo-sacerdotes por 30 moedas de prata. Mais tarde, arrependido, devolveu o dinheiro.", reference: "Mateus 26:14-16", category: .jesus),

    // SALMOS E PROVÉRBIOS
    QuizQuestion(id: 13, question: "Com qual figura o Salmo 23 compara o Senhor?", options: ["Leão", "Águia", "Pastor", "Rocha"], correctIndex: 2, explanation: "'O Senhor é o meu pastor; nada me faltará.' Davi usou a imagem de um pastor para descrever o cuidado amoroso de Deus por seu povo.", reference: "Salmos 23:1", category: .salmos),
    QuizQuestion(id: 14, question: "Quem escreveu a maioria dos Salmos?", options: ["Moisés", "Salomão", "Davi", "Asafe"], correctIndex: 2, explanation: "O rei Davi é o autor de mais da metade dos 150 Salmos. Ele era conhecido como 'o músico suave de Israel' e tinha um coração voltado para Deus.", reference: "2 Samuel 23:1", category: .salmos),
    QuizQuestion(id: 15, question: "Segundo Provérbios, qual é o princípio da sabedoria?", options: ["O amor ao próximo", "O temor do Senhor", "A busca do conhecimento", "A humildade"], correctIndex: 1, explanation: "'O temor do Senhor é o princípio da sabedoria.' Temer a Deus significa respeitá-lo profundamente e viver de acordo com sua vontade.", reference: "Provérbios 9:10", category: .salmos),
    QuizQuestion(id: 16, question: "Quantos Salmos existem na Bíblia?", options: ["100", "120", "150", "180"], correctIndex: 2, explanation: "O livro dos Salmos contém 150 poemas e cânticos de adoração, lamento, gratidão e louvor. É o livro mais longo da Bíblia.", reference: "Livro dos Salmos", category: .salmos),

    // ATOS E CARTAS
    QuizQuestion(id: 17, question: "Qual era o nome original do apóstolo Paulo antes de sua conversão?", options: ["Barnabé", "Silas", "Saulo", "Timóteo"], correctIndex: 2, explanation: "Paulo era chamado de Saulo antes de sua dramática conversão. Ele perseguia os cristãos, mas após encontrar Jesus no caminho de Damasco, tornou-se o maior missionário do evangelho.", reference: "Atos 9:1-19", category: .atos),
    QuizQuestion(id: 18, question: "Quando o Espírito Santo desceu sobre os discípulos no Pentecostes?", options: ["No primeiro dia da semana", "50 dias após a Páscoa", "No dia do Natal", "No dia da Páscoa"], correctIndex: 1, explanation: "O Espírito Santo desceu sobre os discípulos 50 dias após a Páscoa (Pentecostes). Eles receberam línguas de fogo e começaram a falar em outras línguas.", reference: "Atos 2:1-4", category: .atos),
    QuizQuestion(id: 19, question: "Segundo Paulo em 1 Coríntios 13, qual é o maior dos dons?", options: ["A fé", "A esperança", "O amor", "A profecia"], correctIndex: 2, explanation: "'E agora permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor.' O amor é o fundamento de toda a vida cristã.", reference: "1 Coríntios 13:13", category: .atos),
    QuizQuestion(id: 20, question: "Quem era o companheiro missionário de Paulo em sua primeira viagem?", options: ["Pedro", "Barnabé", "Timóteo", "Tito"], correctIndex: 1, explanation: "Barnabé foi o companheiro de Paulo em sua primeira viagem missionária. Ele também foi quem apresentou o recém-convertido Saulo aos apóstolos em Jerusalém.", reference: "Atos 13:2-3", category: .atos),

    // PROFETAS
    QuizQuestion(id: 21, question: "Qual profeta foi engolido por um grande peixe?", options: ["Elias", "Jonas", "Ezequiel", "Jeremias"], correctIndex: 1, explanation: "Jonas fugiu de Deus e foi engolido por um grande peixe. Dentro do peixe por 3 dias e 3 noites, Jonas orou e arrependeu-se. Jesus usou essa história como sinal de sua própria morte e ressurreição.", reference: "Jonas 1:17, Mateus 12:40", category: .profetas),
    QuizQuestion(id: 22, question: "Qual profeta foi levado ao céu em um carro de fogo?", options: ["Eliseu", "Elias", "Daniel", "Isaías"], correctIndex: 1, explanation: "Elias não experimentou a morte física. Um carro de fogo com cavalos de fogo separou Elias de Eliseu, e Elias subiu ao céu em um redemoinho.", reference: "2 Reis 2:11", category: .profetas),
    QuizQuestion(id: 23, question: "Quantas pessoas foram jogadas na fornalha ardente por Nabucodonosor?", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "Sadraque, Mesaque e Abede-Nego foram jogados na fornalha ardente por não adorar a estátua de Nabucodonosor. Mas Deus os protegeu e uma quarta figura apareceu com eles no fogo.", reference: "Daniel 3:19-25", category: .profetas),
    QuizQuestion(id: 24, question: "Qual mar Moisés dividiu para o povo de Israel escapar do Egito?", options: ["Rio Nilo", "Rio Jordão", "Mar Vermelho", "Rio Eufrates"], correctIndex: 2, explanation: "Deus usou Moisés para dividir o Mar Vermelho, permitindo que os israelitas escapassem do exército do Faraó. As águas formaram uma parede dos dois lados.", reference: "Êxodo 14:21-22", category: .profetas),

    // GERAL
    QuizQuestion(id: 25, question: "Quantos livros tem a Bíblia Protestante?", options: ["60", "66", "72", "73"], correctIndex: 1, explanation: "A Bíblia Protestante tem 66 livros: 39 no Antigo Testamento e 27 no Novo Testamento. Esses livros foram escritos por cerca de 40 autores ao longo de 1.500 anos.", reference: "Bíblia Sagrada", category: .geral),
    QuizQuestion(id: 26, question: "Qual é o menor versículo da Bíblia?", options: ["'Orai sempre.' (1 Ts 5:17)", "'Jesus chorou.' (Jo 11:35)", "'Alegrai-vos.' (Fp 4:4)", "'Sede santos.' (1 Pe 1:16)"], correctIndex: 1, explanation: "'Jesus chorou.' (João 11:35) é o versículo mais curto da Bíblia. Mostra a humanidade de Jesus ao lamentar a morte de seu amigo Lázaro.", reference: "João 11:35", category: .geral),
    QuizQuestion(id: 27, question: "Quem era a mãe de Jesus?", options: ["Maria Madalena", "Maria de Betânia", "Maria, mãe de Tiago", "Maria de Nazaré"], correctIndex: 3, explanation: "Maria era uma jovem de Nazaré, prometida em casamento a José, quando o anjo Gabriel a visitou e anunciou que ela conceberia o Filho de Deus pelo Espírito Santo.", reference: "Lucas 1:26-38", category: .geral),
    QuizQuestion(id: 28, question: "Qual foi a linguagem original do Novo Testamento?", options: ["Hebraico", "Aramaico", "Grego", "Latim"], correctIndex: 2, explanation: "O Novo Testamento foi escrito originalmente em grego koiné, a língua comum do mundo mediterrâneo no século I. Isso permitiu que o evangelho se espalhasse amplamente.", reference: "História da Bíblia", category: .geral),
    QuizQuestion(id: 29, question: "Qual mandamento diz 'Honra teu pai e tua mãe'?", options: ["4º", "5º", "6º", "7º"], correctIndex: 1, explanation: "'Honra teu pai e tua mãe' é o quinto mandamento. É o primeiro mandamento com promessa: 'para que se prolonguem os teus dias na terra'. Jesus reafirmou este mandamento nos evangelhos.", reference: "Êxodo 20:12, Mateus 19:19", category: .geral),
    QuizQuestion(id: 30, question: "Em qual livro da Bíblia está o Sermão do Monte?", options: ["Lucas", "João", "Mateus", "Marcos"], correctIndex: 2, explanation: "O Sermão do Monte está em Mateus capítulos 5, 6 e 7. Nele Jesus ensina as bem-aventuranças, o Pai Nosso e muitos dos princípios do Reino de Deus.", reference: "Mateus 5-7", category: .geral)
]
