default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_API_KEY"],
      is_key_content_base64: true
    )

    keychain_name = "match_ci.keychain"
    keychain_password = "MatchCI_Keychain_Pass"
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: false,
      unlock: true,
      timeout: 0,
      add_to_search_list: true
    )

    match(
      type: "appstore",
      app_identifier: ["com.matheusresende.quizbiblico"],
      git_url: ENV["MATCH_GIT_URL"],
      git_branch: "certs-storage",
      api_key: api_key,
      readonly: false,
      force: true,
      generate_apple_certs: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

    profile_mapping = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    UI.message("Profiles: #{profile_mapping}")

    update_code_signing_settings(
      use_automatic_signing: false,
      targets: ["QuizBiblico"],
      code_sign_identity: "Apple Distribution",
      profile_name: profile_mapping["com.matheusresende.quizbiblico"]
    )

    build_number = ENV["GITHUB_RUN_NUMBER"] || "1"
    increment_build_number(build_number: build_number)

    build_app(
      scheme: "QuizBiblico",
      xcargs: {
        "CODE_SIGN_STYLE"    => "Manual",
        "CODE_SIGN_IDENTITY" => "Apple Distribution"
      },
      export_method: "app-store",
      export_options: {
        method: "app-store",
        teamID: "2JFJYD6Z9L",
        signingStyle: "manual",
        provisioningProfiles: profile_mapping
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
